### ISSUE TITLE
title set to Default Text

### ISSUE THREAD

**Issue by williamli** [yasinuslu/blaze-meta#17]
after installing, my site's title became 'Default Title'
I tried setting it in meteor.startup with

	Meta.config({
		  options: {
		    title: "something",
		    suffix: "something else"
		  }
		});

but all my site does is showing Default Title as title

**Comment by williamli** [comment]
calling 
Meta.setTitle("");

after config renders the title correctly, without it, it will show "Default Text"

**Comment by yasinuslu** [comment]
Blaze-meta doesn't currently have iron-router integration. You should call Meta.setTitle and Meta.set methods on iron-router hooks, `onAfterAction` hook would be a good place since the data will be available. You can provide your hooks on [route options](https://github.com/iron-meteor/iron-router/blob/devel/Guide.md#route-specific-options).

I will add an example usage on Readme

**Comment by yasinuslu** [comment]
I saw [lookback:seo](https://atmospherejs.com/lookback/seo) that integrates blaze-meta with iron-router.
